version: "3"
services:
  django:
    build: .
    container_name: test_django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    restart: always
    depends_on:
      - postgres
    command: sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  postgres:
    image: postgres
    container_name: test_pgdb
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: l9l9n
      POSTGRES_PASSWORD: 1
      TZ: UTC
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/

  migration:
    build: .
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate"
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - django


volumes:
  static_volume:
  media_volume: